<?php echo $this->doctype(); ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Grimeland Coding ') ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico?v=2'))
                        ->prependStylesheet($this->basePath() . '/css/grayscale.css')
                        ->prependStylesheet($this->basePath() . '/css/grimeland-coding.css')
                        ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Montserrat:400,700')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">
                    &nbsp;<?php echo $this->translate('Grimeland Coding') ?>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"><?php echo $this->translate('ABOUT') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#services"><?php echo $this->translate('EXPERTISE') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#references"><?php echo $this->translate('REFERENCES') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('CONTACT US') ?></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Content -->
    <?php echo $this->content; ?>

    <!-- Core JavaScript Files -->
    <?php echo $this->inlineScript()            
              ->prependFile($this->basePath() . '/js/jquery.easing.min.js') 
	      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
              ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASTdzJ7gVMQR8CHflCQGTIgzxyepKbihI&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/js/grayscale.js"></script>

</body>
</html>
