<section class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="brand-heading">
	    <?php echo $this->translate(
	    'Corvax Consulting'
	    ) ?>
	  </h1>
          <p class="intro-text">
	    <?php echo $this->translate('
	    The Corvax consulting mission statement. What is Corvax consulting all about. 
	    The mission is to increase code quality, shorten the bridge between management 
	    and developers.
	    ') ?>
	  </p>
          <div class="page-scroll">
            <a href="#about" class="btn btn-circle">
              <i class="fa fa-angle-double-down animated"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="about" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('
	About Corvax
	') ?>
      </h2>
      <p>
	<?php echo $this->translate('
	Who is Corvax, where do we come from. The history of Corvax and 
	why we want to work with clean code. What principles do we work 
	from, what drives us.
	') ?>
      </p>
      <p>
	<?php echo $this->translate('
	If we need to write something more. Vision, mission and ... 
	forgot what it is called. Value statement?
	') ?>
      </p>
      <p>
	<?php echo $this->translate('
	Explain why we are going to change the world of programming forever.
	') ?>
      </p>
    </div>
  </div>
</section>

<section id="services" class="container content-section text-center">
  <div class="service-section">
    <div class="container">
      <div class="col-lg-8 col-lg-offset-2">
        <h2>
	  <?php echo $this->translate('
	  Corvax Services
	  ') ?>			      
	</h2>
        <p>
	  <?php echo $this->translate('
	  What do we offer with Corvax Consulting. What type of consulting.
	  What value do we add. We might want one for consulting, one for 
	  CleanCode injection and one for Corvax Clean Code platform.
	  ') ?>			      
	</p>
      </div>
    </div>
  </div>
</section>

<section id="references" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('
	Corvax Work
	') ?>			      
      </h2>
      <p>
	<?php echo $this->translate('
	Relevant projects we have worked on. The workshop thing in Lima. A good place for references.
	') ?>			      			      
      </p>
    </div>
  </div>
</section>

<section id="team" class="container content-section text-center">
  <div class="team-section">
    <div class="container">
      <div class="col-lg-8 col-lg-offset-2">
        <h2>
	  <?php echo $this->translate('
	  Corvax Team
	  ') ?>			      			      
	</h2>
        <p>
	  <?php echo $this->translate('
	  Martin Grimeland:
	  XXXX XXX XXXXXX:
	  and so on and so forth
	  ') ?>			      			      
	</p>
      </div>
    </div>
  </div>
</section>

<section id="contact" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('
	Contact Corvax
	') ?>			      			      
      </h2>
      <p>
	<?php echo $this->translate('
	Feel free to email us if you want to know more about our services 
	or if you just want to talk about best practises and clean code.
	') ?>			      			      
      </p>
      <p>martin.grimeland@gmail.com</p>
      <ul class="list-inline banner-social-buttons">
        <li><a href="https://twitter.com/corvaxcoding" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
        </li>
        <li><a href="https://github.com/martin.grimeland" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
        </li>
        <li><a href="https://plus.google.com/+martin.grimeland/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
        </li>
      </ul>
    </div>
  </div>
</section>

<div id="map"></div>
