<section class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="brand-heading">
	    <?php echo $this->translate(
	    'Grimeland Coding'
	    ) ?>
	  </h1>
          <p class="intro-text">
	    <?php echo $this->translate('elevator pitch grimeland coding') ?>
	  </p>
          <div class="page-scroll">
            <a href="#about" class="btn btn-circle">
              <i class="fa fa-angle-double-down animated"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="about" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('About Grimeland Coding') ?>
      </h2>
      <p class="about-text">
 	<?php echo $this->translate('who is grimeland coding intro') ?>
      </p>
      <p class="about-text">
	<?php echo $this->translate('who is grimeland coding 1') ?>
      </p>
      <p class="about-text">
	<?php echo $this->translate('who is grimeland coding 2') ?>
      </p>
      <p class="about-text">
	<?php echo $this->translate('who is grimeland coding 3') ?>
      </p>
    </div>
  </div>
</section>

<section id="services" class="container content-section text-center">
  <div class="service-section">
        <h2>
	  <?php echo $this->translate('Expertise') ?>			      
	</h2>
    <div class="container lead-developer">
      <div class="col-lg-8 col-lg-offset-2">
        <h3>
	  <?php echo $this->translate('Lead Developer') ?>			      
	</h3>
        <p class="collapse" id="view-lead-developer-description">
	  <?php echo $this->translate('describe grimeland coding lead developer') ?>			      
	</p>
	<p>
	  <a class="btn showdetails" data-toggle="collapse" data-target="#view-lead-developer-description">
	     <?php echo $this->translate('Describe lead developer') ?>
          </a>
        </p>
        <p>
	  <?php echo $this->translate('describe strength as lead developer') ?>			      
	</p>
      </div>
    </div>
    <div class="container">
      <div class="col-lg-8 col-lg-offset-2">
        <h3>
	  <?php echo $this->translate('Senior System Developer') ?>			      
	</h3>
        <p class="collapse" id="view-developer-description">
	  <?php echo $this->translate('describe grimeland coding senior system developer') ?>			      
	</p>
	  <p>
            <a class="btn showdetails" data-toggle="collapse" data-target="#view-developer-description">
  	      <?php echo $this->translate('Describe Senior System Developer') ?>			      
	    </a>
	  </p>
        <p>
	  <?php echo $this->translate('describe strength as senior system developer') ?>			      
	</p>
      </div>
    </div>
    <div class="container agile-coach">
      <div class="col-lg-8 col-lg-offset-2">
        <h3>
	  <?php echo $this->translate('Agile Coach') ?>			      
	</h3>
        <p class="collapse" id="view-agile-coach-description">
	  <?php echo $this->translate('describe grimeland coding agile coach') ?>			      
	</p>
	<p>
	  <a class="btn showdetails" data-toggle="collapse" data-target="#view-agile-coach-description">
	  <?php echo $this->translate('Describe Agile Coach') ?>			      
	  </a>
	</p>
        <p>
	  <?php echo $this->translate('describe strength as coding agile coach') ?>			      
	</p>
      </div>
    </div>
  </div>
</section>

<section id="references" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('References') ?>			      
      </h2>
        <h3>
	  <?php echo $this->translate('Sysco AS') ?><img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/Sysco_logo_300px.png') ?>" alt=""/>
	</h3>
        <p>
	  <?php echo $this->translate('describe grimeland coding sysco as') ?>			      
	</p>
        <h4>
	  <?php echo $this->translate('Vidum AS') ?>			      
	</h4>
        <p>
	  <?php echo $this->translate('describe grimeland coding vidum') ?>			      
	</p>
        <h4>
	  <?php echo $this->translate('PPlan') ?>			      
	</h4>
        <p>
	  <?php echo $this->translate('describe grimeland coding pplan') ?>			      
	</p>
        <h3>
	  <?php echo $this->translate('Grimeland Coding') ?>
	</h3>
        <p>
	  <?php echo $this->translate('describe grimeland coding') ?>			      
	</p>
        <h4>
	  <?php echo $this->translate('Avspark.no') ?>	
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/ABCStartsidenLogo.jpg') ?>" alt=""/>
	</h4>
        <p>
	  <?php echo $this->translate('describe grimeland coding avspark') ?>			      
	</p>
        <h3>
	  <?php echo $this->translate('Orchestration AS') ?>			      
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/OrchestrationLogo.png') ?>" alt=""/>
	</h3>
        <p>
	  <?php echo $this->translate('describe grimeland coding orchestration') ?>			      
	</p>
        <h4>
	  <?php echo $this->translate('MeeTV') ?>			      
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/MeeTvLogo.png') ?>" alt=""/>
	</h4>
        <p>
	  <?php echo $this->translate('describe grimeland coding meetv') ?>			      
	</p>
        <h4>
	  <?php echo $this->translate('Norsk-Tipping') ?>			      
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/Norsk-TippingLogo.jpg') ?>" alt=""/>
	</h4>
        <p>
	  <?php echo $this->translate('describe grimeland coding Norsk Tipping') ?>			      
	</p>
        <h4>
	  <?php echo $this->translate('Conductor') ?>			      
	</h4>
        <p>
	  <?php echo $this->translate('describe grimeland coding conductor') ?>			      
	</p>
        <h3>
	  <?php echo $this->translate('Onsite Solutions AS') ?>			      
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/onsite-logo-160-shadow.png') ?>" alt=""/>
	</h3>
        <p>
	  <?php echo $this->translate('describe grimeland coding onsite') ?>			      
	</p>
    </div>
  </div>
</section>

<section id="contact" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('contact grimeland coding') ?>			      			      
      </h2>
      <p>
	<?php echo $this->translate('contact-motivation') ?>			      			      
      </p>
      <p>martin.grimeland@gmail.com</p>
      <ul class="list-inline banner-social-buttons">
        <li><a href="https://twitter.com/corvaxcoding" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
        </li>
        <li><a href="https://github.com/martin.grimeland" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
        </li>
        <li><a href="https://plus.google.com/+MartinGrimeland/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
        </li>
      </ul>
    </div>
  </div>
</section>

<div id="map"></div>
