<section class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="brand-heading">
	    <?php echo $this->translate(
	    'Grimeland Coding'
	    ) ?>
	  </h1>
          <p class="intro-text">
	    <?php echo $this->translate('elevator pitch grimeland coding') ?>
	  </p>
          <div class="page-scroll">
            <a href="#about" class="btn btn-circle">
              <i class="fa fa-angle-double-down animated"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="about" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('About Grimeland Coding') ?>
      </h2>
      <p class="about-text">
 	<?php echo $this->translate('who is grimeland coding intro') ?>
      </p>
      <p class="about-text">
	<?php echo $this->translate('who is grimeland coding 1') ?>
      </p>
      <p class="about-text">
	<?php echo $this->translate('who is grimeland coding 2') ?>
      </p>
      <p class="about-text">
	<?php echo $this->translate('who is grimeland coding 3') ?>
      </p>
    </div>
  </div>
</section>

<section id="services" class="container content-section text-center">  
  <div class="container-fluid service-section">
    <div class="row">
      <h2>
	<?php echo $this->translate('Expertise') ?>			      
      </h2>
      <div class="col-xs-12 col-sm-6">
        <h3>
	  <?php echo $this->translate('Lead Developer') ?>			      
	</h3>
	<button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		data-toggle="collapse" data-target="#view-lead-developer-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	</button>
        <div class="collapse" id="view-lead-developer-description">
          <p>
	    <?php echo $this->translate('describe grimeland coding lead developer') ?>			      
	  </p>
          <p>
	    <?php echo $this->translate('describe strength as lead developer') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6">
	<h3>
	  <?php echo $this->translate('Senior System Developer') ?>			      
	</h3>
	<button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		data-toggle="collapse" data-target="#view-developer-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	</button>
	<p>
	</p>
	<div class="collapse" id="view-developer-description">
          <p>
	    <?php echo $this->translate('describe grimeland coding senior system developer') ?>			      
	  </p>
          <p>
	    <?php echo $this->translate('describe strength as senior system developer') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <h3>
	  <?php echo $this->translate('Agile Coach') ?>			      
	</h3>
	<button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		data-toggle="collapse" data-target="#view-agile-coach-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	</button>
        <div class="collapse" id="view-agile-coach-description">
          <p>
	    <?php echo $this->translate('describe grimeland coding agile coach') ?>			      
	  </p>
          <p>
	    <?php echo $this->translate('describe strength as coding agile coach') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <h3>
	  <?php echo $this->translate('Clean Code Workshops') ?>			      
	</h3>
	<button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		data-toggle="collapse" data-target="#view-clean-code-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	</button>
        <div class="collapse" id="view-clean-code-description">
          <p>
	    <?php echo $this->translate('describe grimeland coding agile coach') ?>			      
	  </p>
          <p>
	    <?php echo $this->translate('describe strength as coding agile coach') ?>			      
	  </p>
	</div>
      </div>
    </div>
  </div>
</section>

<section id="references" class="container content-section text-center">
  <div class="container-fluid">
    <div class="row">
      <h2>
	<?php echo $this->translate('References') ?>			      
      </h2>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/Sysco_logo_only.png') ?>" alt=""/>
	  <?php echo $this->translate('Sysco AS') ?>
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-sysco-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	</h4>
        <div class="collapse" id="view-sysco-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding sysco as') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
	<h4>	  
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/vidum.jpg') ?>" alt=""/>
	  <?php echo $this->translate('Vidum AS') ?>			      
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-vidum-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	</h4>
        <div class="collapse" id="view-vidum-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding vidum') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/Sysco_logo_only.png') ?>" alt=""/>
	  <?php echo $this->translate('PPlan') ?>			 
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-pplan-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	  
	</h4>
        <div class="collapse" id="view-pplan-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding pplan') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/OrchestrationLogo.png') ?>" alt=""/>
	  <!-- <?php echo $this->translate('Orchestration AS') ?>	 -->
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-orchestration-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	  
	</h4>
        <div class="collapse" id="view-orchestration-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding orchestration') ?>
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/MeeTvLogo.png') ?>" alt=""/>
	  <!-- <?php echo $this->translate('MeeTV') ?>			      -->
 	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-meetv-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	</h4>
        <div class="collapse" id="view-meetv-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding meetv') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-sm-12 col-md-6">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/onsite-logo-160-shadow.png') ?>" alt=""/>
	  <?php echo $this->translate('Onsite Solutions AS') ?>  
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-onsite-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	</h4>
        <div class="collapse" id="view-onsite-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding onsite') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/ABCStartsidenLogo.jpg') ?>" alt=""/>
	  <?php echo $this->translate('Avspark.no') ?>	
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-avspark-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	</h4>
        <div class="collapse" id="view-avspark-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding avspark') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/OrchestrationLogo_only.png') ?>" alt=""/>
	  <?php echo $this->translate('Conductor') ?>			      
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-conductor-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	</h4>
        <div class="collapse" id="view-conductor-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding conductor') ?>			      
	  </p>
	</div>
      </div>
      <div class="col-sm-12 col-md-5">
	<h4>
	  <img class="reference-img" src="<?php echo $this->basePath('img/grimeland-coding/Norsk-TippingLogo.jpg') ?>" alt=""/>
	  <?php echo $this->translate('Norsk-Tipping') ?>		
	  <button type="button" class="btn btn-default btn-xs showdetails collapsed" 
		  data-toggle="collapse" data-target="#view-norsk-tipping-description">
	  <span class="fa fa-angle-double-down"></span>
	  <span class="fa fa-angle-double-up"></span>
	  </button>
	  
	</h4>
        <div class="collapse" id="view-norsk-tipping-description">
	  <p>
	    <?php echo $this->translate('describe grimeland coding Norsk Tipping') ?>			      
	  </p>
	</div>
      </div>
    </div>
  </div>
</section>

<section id="contact" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>
	<?php echo $this->translate('contact grimeland coding') ?>			      			      
      </h2>
      <p class="center-text">
	<?php echo $this->translate('contact-motivation') ?>			      			      
      </p>
      <p class="center-text">martin.grimeland@gmail.com</p>
      <ul class="list-inline banner-social-buttons">
        <li><a href="https://twitter.com/corvaxcoding" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
        </li>
        <li><a href="https://github.com/martin.grimeland" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
        </li>
        <li><a href="https://plus.google.com/+MartinGrimeland/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
        </li>
      </ul>
    </div>
  </div>
</section>

<div id="map"></div>
